### ISSUE TITLE
Can't deserialize string properties!!!

### ISSUE THREAD

**Issue by mss37** [lukasz-pyrzyk/BinaryFormatter#1]
I am getting this exception when trying to deserialize string properties:
System.MissingMethodException: 'No parameterless constructor defined for this object.'

Potentially because of this problem:
https://stackoverflow.com/questions/2092530/how-do-i-use-activator-createinstance-with-strings

**Comment by YPermitin** [comment]
@mss37 Could you show sample of class with this problem?

**Comment by YPermitin** [comment]
@lukasz-pyrzyk Did you fix this problem? I see some fixes at here bd3a0de5b0be0c6a67c6845061e8a27e49abc495

**Comment by lukasz-pyrzyk** [comment]
Yup, this error is fixed. I will close the issue, please comment in case of any problems
