### ISSUE TITLE
Use stream instead of byte[]

### ISSUE THREAD

**Issue by YPermitin** [lukasz-pyrzyk/BinaryFormatter#10]

**Comment by YPermitin** [comment]
By info @lukasz-pyrzyk 
"I wrote a "BufferedStream", please take look: https://github.com/lukasz-pyrzyk/Kronos/blob/master/Src/Kronos.Core/Pooling/BufferedStream.cs

This stream is able to be reset and reuse working memory or use any given ArrayPool<T>"

**Comment by lukasz-pyrzyk** [comment]
Please go forward with classic memory stream (but hidded as stream). We can investirage BufferedStream in future.

**Comment by YPermitin** [comment]
@lukasz-pyrzyk Okey

**Comment by lukasz-pyrzyk** [comment]
@YPermitin do you think it is currently necessary to rewrite deserialization with streams?

**Comment by YPermitin** [comment]
@lukasz-pyrzyk I am agree, that it will be quite heavy to change. Let's save current version of deserialisation and will up this question in the next versions if it will be necessary.
Do you agree?

**Comment by lukasz-pyrzyk** [comment]
Yes, i agree :) Closing the issue
