### ISSUE TITLE
Release 2.0.0

### ISSUE THREAD

**Issue by lukasz-pyrzyk** [lukasz-pyrzyk/BinaryFormatter#53]
I'm thinking about earlier release of the 2.0, because remaining stories are about adding more types, where the biggest change in protocol is already done. Am I wrong @YPermitin ?

**Comment by YPermitin** [comment]
@lukasz-pyrzyk Yes, most of issues are already done and 2.0 can be released.

But we have open question about compatibility 1.x and 2.0 version.
Potential problems:
- (de)serializing for objects, becouse CustomObjectConverter was added.
- We change format of binary data for saving (de)serialization data.

What are you thinking about that? How we can tell for uesrs of library, that version 2.0 is a new way to work and old stored data not compability with it?

**Comment by lukasz-pyrzyk** [comment]
In semantic versioning, minor update can be incompatible with previous versions. 
I can put a note in release notes here at github and at the nuget page:
![image](https://user-images.githubusercontent.com/5083018/28610513-d6670920-71e8-11e7-801b-195f4885270b.png)

I would prefer faster release, because we have few bugfixes :)

**Comment by YPermitin** [comment]
@lukasz-pyrzyk yes....bugs is not good (;

Ok) Let's released! =)

**Comment by YPermitin** [comment]
@lukasz-pyrzyk Congratulations!
